pelias/openstreetmap

- package.json
- stream/document_constructor.js
- test/stream/document_constructor.js
catch model errors, avoid fatal error exit(1), resolves #42
> catch model errors, avoid fatal error exit(1), resolves #42

- stream/address_extractor.js
- test/stream/address_extractor.js
Following on from discussion in https://github.com/pelias/openstreetmap/pull/52
> Error handling

- package.json
bump `pbf2json` dependency to latest version which supports `OSX`.
> add OSX support

- .gitignore
- .jshintignore
- README.md
- package.json
> Add code coverage reporting

- config/category_map.js
- test/fixtures/vancouver.extract.expected.json
> update taxonomy to maintain conformity with geonames

- stream/address_extractor.js
- test/fixtures/docs.js
- test/stream/address_extractor.js
fixes: https://github.com/pelias/openstreetmap/issues/21
note: I had to refactor the property mapping functions due to jshint warnings
> support for semi-colon delimited house numbers

- package.json
- test/fixtures/vancouver.extract.expected.json
upgrade to latest version of pbf2json
> update to latest version of pbf2json

- package.json
- test/end-to-end.js
better end-to-end reporting for pass/fail
> better end-to-end reporting for pass/fail

- stream/tag_mapper.js
- test/fixtures/vancouver.extract.expected.json
- test/stream/tag_mapper.js
> allow closing brackets. resolves #47

- schema/address_tiger.js
- stream/tag_mapper.js
resolves https://github.com/pelias/openstreetmap/issues/74
> add tiger address mapping config

- config/category_map.js
because who doesn't love burrito, am I right @missinglink ?
> adding burrito

- README.md
- index.js
- package.json
- stream/address_extractor.js
- stream/category_mapper.js
- stream/denormalizer.js
- stream/document_constructor.js
- test/end-to-end.js
- test/fixtures/docs.js
- test/stream/address_extractor.js
- test/stream/category_mapper.js
- test/stream/document_constructor.js
- test/stream/tag_mapper.js
- test/travis-config.js
New ids should be as follows:
for named POI (venue): 
`_id` = `[node | way]:[osm-id]`
`_type` = `venue`
`data.category` = will have categories
for addresses: 
`_id` = `[node | way]:[osm-id]`
`_type` = `address`
`data.category` = will have __NO__ categories
for addresses with multiple house numbers: 
`_id` = `[node | way]:[osm-id]:[housenum]`
`_type` = `address`
`data.category` = will have __NO__ categories
Fixes pelias/pelias#227
> Update id building scheme and add logging

- index.js
- package.json
Connected to pelias/wof-admin-lookup#21
> Update pelias-wof-admin-lookup and remove process.exit temp hack

- package.json
- schema/address_karlsruhe.js
- schema/address_naptan.js
- schema/address_osm.js
- schema/address_tiger.js
- stream/address_extractor.js
- test/fixtures/docs.js
- test/stream/address_extractor.js
- test/stream/category_mapper.js
- test/stream/tag_mapper.js
> Rename address prop

- stream/adminLookup.js
- stream/deduper.js
- util/sendPassthroughStream.js
This is mostly just a stylistic change. The code makes more sense this way
(for me at least)
> Cleaning up code for OSM importer

- package.json
Closes #242
https://greenkeeper.io/
> fix(package): update pelias-wof-admin-lookup to version 3.1.2

- package.json
> fix(package): update pelias-wof-admin-lookup to version 3.7.0

- package.json
> fix(package): update pelias-wof-admin-lookup to version 3.10.2

- package.json
> chore(package): update semantic-release to version 8.0.1

- package.json
> Move `async` to dependencies from devDependencies

- package.json
This is required for HTTP PIP support!
> Upgrade to pelias-wof-admin-lookup 4.3.0

- package.json
- stream/tag_mapper.js
Replaces trimmer dependency with `lodash.trim`
> removed trimmer dependency in favor of lodash

- .travis.yml
- package.json
- stream/tag_mapper.js
- test/stream/tag_mapper.js
A long requested feature added in 10 lines of code :)
I bundled in a node upgrade to pad it out a bit!
> Index airport codes

- stream/importPipeline.js
remove log line missed in: https://github.com/pelias/openstreetmap/pull/347
> fix(logger): remove logger line

- README.md
- config/features.js
- schema.js
- stream/multiple_pbfs.js
- stream/pbf.js
- test/config/features.js
- test/stream/pbf.js
I opened this PR after reviving and cleaning up https://github.com/pelias/openstreetmap/pull/382
thanks @jbgriesner for the original PR :)
> feat(venue): Add option to disable venue import

- .editorconfig
This is an initial .editorconfig file for pelias.
> Initial .editorconfig file

- .gitignore
- package.json
Updated `pelias/pbf2json` dependency to bring in https://github.com/pelias/pbf2json/pull/77
> pbf2json bugfix pbf2json/pull/77

- package.json
- test/end-to-end.js
> remove unused npm module

- util/parseSemicolonDelimitedValues.js
It's important to preserve a link to history even if its time has passed 😆
> Memorialize The Most Clever Line of Javascript
