pelias/openstreetmap

- stream/address_extractor.js
- stream/category_mapper.js
- stream/tag_mapper.js
- test/stream/address_extractor.js
- test/stream/category_mapper.js
- test/stream/tag_mapper.js
A bunch of improvements regarding error handling:
- gracefully handle newline and tab characters in OSM tag values
- catch generic thrown errors in stream transform functions
Plus some minor tweaks:
- rename `item` to `doc` for consistency ($doc represents a `pelias/model.Document` object)
- rename `done` to `next`, again for consistency
- flatten some nested code to reduce cyclomatic complexity
- add more tests to cover more edge-cases
> Error handling

- stream/address_extractor.js
Some modifications to `stream/address_extractor.js`: reduce the scope of the overarching `try`/`catch` block and use `Document` getters/setters.
Fixes #56
> Use document getters#56

- package.json
- stream/address_extractor.js
- stream/category_mapper.js
- stream/denormalizer.js
- stream/document_constructor.js
- stream/stats.js
- stream/tag_mapper.js
Resolve #36 .
```
package.json
-Add `pelias-logger` as a dependency.
stream/(address_extractor, category_mapper, denormalizer, document_constructor, stats, tag_mapper).js
-Replace all usage of `console` with `pelias-logger`.
```
> Replace use of console with pelias-logger.

- package.json
- stream/denormalizer.js
- stream/document_constructor.js
- test/fixtures/docs.js
- test/stream/denormalizer.js
- test/stream/document_constructor.js
bring osm importer up-to-date with latest changes to `osm2pbf`, see https://github.com/pelias/pbf2json/pull/23
the gist of the changes is that we use the precomputed centroid passed in from the Go library where available to avoid doing those calcs in the nodejs process.
there is also some cleaning up and adding of tests to cover the centroid functionality
the result should be a faster and more stable build, plus we can potentially remove the one last piece of code in this repo which is not very well tested.
> upgrade pbf2json

- README.md
- index.js
- package.json
Hi,
Currently there is no possibility of using the address-deduplicator on openstreetmap addresses, as you can do with openaddresses. This adds the possibility of using pelias/address-deduplicator in the input stream to filter out already-seen addresses.
> Use Address-deduplicator

- stream/adminLookup.js
Since [pelias/config](https://github.com/pelias/config) doesn't yet contain a default section for adminLookup (and there probably won't be a public Who's on First point in polygon server for a while), the default experience for setting up an importer is to get an error. See #93.
This PR tries to gracefully handle some different config combinations and, in the case where admin lookup is enabled for OSM but there's no point in polygon server URL set, print an error message that hopefully points users in the right direction. I'd really love suggestions for how to improve this error message even more.
Fixes #93
> Add helpful error message when adminLookup is misconfigured

- stream/adminLookup.js
Now that we are back to using a local admin lookup service, this
configuration checking is a bit too aggressive.
Fixes pelias/whosonfirst#38
> Remove requirement to set adminLookup URL

- stream/adminLookup.js
- test/stream/adminLookup.js
The admin lookup stream code was incorrectly checking the wrong
property, making it harder to enable admin lookup.
Thanks to @DylanFrese for helping us figure this out.
Related: pelias/wof-admin-lookup#52
Fixes pelias/wof-admin-lookup#51
> Check the proper admin lookup config properties

- package.json
This is in line with https://github.com/pelias/pelias/issues/366, where
we decided to only use exact version deps for other Pelias code. This
both helps us track changes better, and ensure we can know exactly what
code we're releasing at any time.
> Require exact version of pbf2json

- README.md
Documentation specified the old way of enabling adminLookup
> fixed documentation on adminLookup

- config/features.js
- test/config/features.js
reduce target `aeroway` values to only those enumerated in a whitelist
see issue https://github.com/pelias/pelias/issues/573 for more detail.
this PR changes our broad `aeroway+name` filter to a more selective one.
more notes on the issue linked above.
closes https://github.com/pelias/pelias/issues/573
> feature whitelist - re: aeroway

- stream/importPipeline.js
the spy stream logs each new record, this PR simply changes the log level from info->verbose.
```bash
info: [openstreetmap-points] openstreetmap:address:node:342701864 5 Klitmøllervej lon=8.670321, lat=56.983651
info: [openstreetmap-points] openstreetmap:address:node:340582720 1 Bakkehegnet lon=12.391713, lat=55.757433
info: [openstreetmap-points] openstreetmap:address:node:340801972 20 Rønnebærkæret lon=12.278787, lat=55.585956
info: [openstreetmap-points] openstreetmap:address:node:341725570 87 Sankt Jørgens Vej lon=10.595304, lat=55.051658
info: [openstreetmap-points] openstreetmap:address:node:342488055 209 Skovvej lon=9.711022, lat=55.561912
info: [openstreetmap-points] openstreetmap:address:node:342701866 9 Klitmøllervej lon=8.667341, lat=56.985503
info: [openstreetmap-points] …
```
> logging: change spy log level from info->verbose

- package.json
- stream/importPipeline.js
This log will generate over 10GB of output on _every_ full planet build.
It was useful for analyzing builds, but that sort of analysis could also
easily be done as a separate task that would complete much faster than a
build.
Replaces https://github.com/pelias/openstreetmap/pull/339
> Remove very noisy centroid logging

- .circleci/docker.sh
As featured in other PRs such as https://github.com/pelias/schema/pull/243, there was an error in the Docker build script that caused it to do nothing.
> Fix Docker build script

- README.md
- util/download_data.js
We have curl configured to redirect, but this will ensure HTTPS is the default, which is definitely a good thing.
Fixes #396
> Default to HTTPS for planet file download

- stream/address_extractor.js
This is not really an error, as it's the expected behavior when there is not enough data in a venue record to also create an address record.
The resulting output is both extremely verbose and potentially confusing to users.
> Remove 'Invalid doc not pushed downstream' error

- .jshintrc
- schema/name_osm.js
- stream/tag_mapper.js
- test/stream/tag_mapper.js
this PR allows OSM tags to be mapped as aliases of the `name.default` field.
the `schema/name_osm.js` file contains a mapping of OSM tags to `name.*` fields.
prior to this PR we were only able to map 1:1 from OSM to the Pelias model.
this PR now supports multiple values in that object set as `default`, in this case the additional tags will be mapped as aliases of the `name.default` field.
the configuration also adds an additional inenumerable property called `_primary` which defines which of those is considered the 'primary' name.
an example tag mapping:
```
osm_tags = { name: "foo", short_name: "bar", reg_name: "baz" }
name = {
default: "foo",
short: "bar",
regional: "baz"
}
name = {
default: [ "foo", "bar" ],
regional: "baz"
}
```
---
I enabled 3 tags as aliases of default: `[ …
> support for mapping tags to name.default aliases

- bin/test
- package.json
The way we were running our unit tests does not catch fatal errors in the unit test run, even though they return non-zero status codes. By using a dedicated script to run the tests, with the `pipefail` option,
we can catch them.
Connects https://github.com/pelias/pelias/issues/744
> feat(test): Use test script to catch errors

- Dockerfile
This was added in https://github.com/pelias/openstreetmap/pull/454 and while it may be nice to have importer containers know how to start themselves, it means that running `pelias compose up` (or
`docker-compose up`) in the pelias/docker repo would _always_ start all the importers.
With that in mind, it's best to leave this off for now, and have the `pelias` executable know to call `./bin/start` on each importer.
> fix(docker): remove default Docker command

- util/download_data.js
Similar to https://github.com/pelias/whosonfirst/pull/397, since `pelias/docker` often runs multiple downloads in parallel, it's nice if this downloader is explicit that it's downloading data for OpenStreetMap.
> feat(download): clarify importer name when downloading

- Dockerfile
When running the end-to-end tests, LevelDB (via `pbf2json`) leaves behind its data in /tmp, and does not clean itself up.
Future containers run using this image will almost certainly also run `pbf2json`, and may not run using the same user id, meaning permissions to overwrite the files in `/tmp` may not exist. Thus, it's best if they
are removed in the Docker image.
Connects https://github.com/pelias/pelias/issues/745
Connects https://github.com/pelias/docker/pull/20
> fix(docker): Clean up files left from running tests

- package.json
- stream/importPipeline.js
This allows distinguishing which logger output lines correspond to which
importer during an import.
Connects https://github.com/pelias/dbclient/issues/101
> feat(logger): Use dbclient name functionality

- stream/document_constructor.js
- test/stream/document_constructor.js
BREAKING CHANGE
OpenStreetMap effectively has an ID structure composed of two parts: a record type specifier (node, way, relation) and a numeric identifier. Both are needed because there is often overlap between the numeric identifiers of different types.
For a long time, Pelias has used the OSM record type and numeric identifier to construct Pelias GIDs. The character chosen to separate the OSM type and ID was `:`, which is the same as the separator between parts of a Pelias GID.
This lead to two relatively minor problems:
1. It causes confusion as to the structure of Pelias GIDs. The official format is `source:layer:id`, but when the `id` itself also has a colon in it, there's the potential for confusion both for people attempting to
understand the structure, and for code attempting to …
> feat(ids): Change ID section separator to forward slash

- stream/addendum_mapper.js
- stream/importPipeline.js
- test/end-to-end.js
- test/run.js
- test/stream/addendum_mapper.js
- test/stream/importPipeline.js
This is a feature I've been wanting for some time.
This PR adds some selected OSM tags to the addendum for each record.
For now, the whitelist is:
```
const whitelist = [
'wheelchair', // Wheelchair accessibility
'iata', // IATA airport codes
'icao', // ICAO airport codes
'wikidata', // Wikidata concordance
'wikipedia', // Wikipedia concordance
// 'website', // Website URL
// 'phone', // Telephone number
// 'opening_hours', // Opening hours
];
```
I commented out the contact details and opening hours, for now, let's see how much disk space these smaller fields consume before we uncomment the other ones.
also open to import some other fields but let's not go crazy and import all of OSM, only concordances and tags directly related to geocoding will be accepted.
example: …
> add selected tags to addendum

- config/features.js
Pedestrian squares are often well known places that are essentially venues. This change allows any OSM record with the tags `highway=pedestrian`, `area=yes`, and a name to be imported as a venue.
> feat(features): Add pedestrian squares

- package.json
- test/stream/address_extractor.js
Replacing `event-stream` with `stream-mock` as discussed in https://github.com/pelias/pelias/issues/801
> tests(address-extractor) replace event-stream with stream-mock

- stream/tag_mapper.js
- test/stream/tag_mapper.js
resolves https://github.com/pelias/openstreetmap/issues/497
> use "name:en" as a fallback for when no default name was found

- package.json
As of `pelias-config@4.8.0`, the default Elasticsearch type name is now `_doc`, which is the value compatible with Elasticsearch 7.
This PR updates the functional tests to expect that new value.
Connects https://github.com/pelias/config/pull/122
Connects https://github.com/pelias/pelias/issues/831
Fixes https://github.com/pelias/openstreetmap/issues/513
> chore(tests): Update test expectations for new doc type name

- stream/address_extractor.js
If using the `verbose` log level or above, this importer will print many log lines like the following:
```
2020-04-22T02:34:12.254Z - verbose: [openstreetmap] [address_extractor]
duplicating a venue with address
2020-04-22T02:34:12.254Z - verbose: [openstreetmap] [address_extractor]
duplicating a venue with address
```
These log lines don't really add any value, as they record an extremely normal and common occurrence.
If we wanted to count how many address records came from duplicating a venue, we could do so, but it might make more sense to print a single count at the end.
> feat(logs): Remove verbose address extractor log

- config/features.js
- stream/addendum_mapper.js
- test/config/features.js
- test/stream/addendum_mapper.js
Closes #527 
I tested locally using the `portland-metro` project data (504k total records; 36621 venues); after adding brand + operator to the addendum the index size grew by ~0.27% (+~0.3 MB, from 111.95mb -> 112.25mb).
When updating the data used by the end-to-end tests I noticed a couple of new addresses were contained in the output, which I wasn't really expecting...  they appear to be addresses indexed from new venues that were pulled in, eg `relation/6066047`.   I assume this is expected; let me know if not.
Thanks!
> Add two new OSM venue tags; add operator/brand to addendum

- config/features.js
- stream/addendum_mapper.js
- test/config/features.js
- test/stream/addendum_mapper.js
following on from https://github.com/pelias/openstreetmap/pull/528 this PR uncomments the three fields I wanted to enable in the past but wasn't sure how much additional disk space would be required.
turns out that addendum fields don't add a lot of bytes.
I also took the liberty to modernize the codebase a bit and fix a test case that wasn't being run due to using a duplicate variable name.
> additional addendum fields

- package.json
We want to ensure the fix for https://github.com/pelias/wof-admin-lookup/issues/288, contained in https://github.com/pelias/wof-admin-lookup/pull/297, is used when importing.
> fix(deps): Upgrade wof-admin-lookup to the latest

- stream/addendum_mapper.js
As the first and most obvious step in returning data useful due to COVID-19, we can add some relevant [OSM Tags](https://wiki.openstreetmap.org/wiki/Covid-19_-_how_to_map#Summary_of_main_keys).
Connects https://github.com/pelias/pelias/issues/869
> feat: Add `covid19` OSM tags as addendum data

- stream/importPipeline.js
- stream/popularity_mapper.js
- stream/tag_mapper.js
- test/end-to-end.js
- test/run.js
- test/stream/importPipeline.js
- test/stream/popularity_mapper.js
- test/stream/tag_mapper.js
This PR builds on #493 with a couple additions I think might help our existing set of test cases. I'm sure we could think of more to add!
Closes pelias/pelias#171
Closes https://github.com/pelias/openstreetmap/pull/493
> Venue popularity additions

- README.md
- stream/popularity_mapper.js
- test/stream/popularity_mapper.js
As described in https://github.com/pelias/openstreetmap/issues/537, the default set in https://github.com/pelias/openstreetmap/pull/493, where all venues that have a calculated popularity below `0` are not imported,
is a bit strict.
This adds a config flag, `imports.openstreetmap.removeDisusedVenues` that controls whether or not that behavior is activated.
In addition, when enabled, a `warning` is displayed for each removed record.
> Add configuration option to control venue removal

- schema/name_osm.js
- stream/tag_mapper.js
- test/stream/tag_mapper.js
These language codes (`international`, `national`, `old` ... etc) were included in the build years ago and never utilised in query logic.
Let's remove them from the index since they're just taking up space?
note: I had to change the tag mapper slightly to ensure the work from https://github.com/pelias/openstreetmap/pull/498 didn't break.
> remove language codes we never used

- stream/address_extractor.js
- test/stream/address_extractor.js
there is an error in the logic for handling semicolon delimited housenumbers, resulting in results such as this:
https://pelias.github.io/compare/#/v1/search?text=1336+Parker+STREET+Berkeley%2C+CA+94702+USA
this PR ensures that:
- each `address` record only contains a single housenumber
- the `venue` record takes only the first housenumber
> improved handling of semicolon delimited housenumbers

- stream/address_extractor.js
- test/stream/address_extractor.js
while working on https://github.com/pelias/openstreetmap/pull/546 I noticed this, which might be a bug, might be intended, not sure.
a single OSM record can become multiple records in Pelias.
ie. it can become a single `venue` and multiple `address` records.
so we generate a unique ID for each of those records in Pelias.
what's currently happening here is the first `address` has the same ID as the `venue` (if there is one), since its on a different layer it'll get a different GID, all good.
for *subsequent* address records we append the **housenumber value** to the ID:
I think that is a bit dangerous since the housenumber field is a freeform OSM string which could contain all sorts of characters such as spaces, or `:` which is used as a delimiter in the GID scheme.
This PR changes that to …
> use array offset instead of value for address ID generation

- stream/popularity_mapper.js
- test/stream/popularity_mapper.js
this is a fairly simple PR which sets a popularity value for `address` records which are 'popular' by some metric (usually they list contact details or have other metadata denoting that they are a venue).
prior to this PR *only* `venue` records would receive a `popularity`.
this work is motivated by this testcase which returns two valid addresses in Sydney but doesn't put the Sydney Opera House address first (inspecting the ES response shows the scores are currently identical).
with this PR a very small scoring difference will occur which will tip the balance in the favour of the Opera House.
note: I have clamped the `popularity` for `address` records to a max of 1000, I didn't want to introduce a wide range of variability in the scoring for them, the rationale for this is discussed in …
> set popularity on some address records

- stream/popularity_mapper.js
- test/stream/popularity_mapper.js
As per https://github.com/pelias/geonames/pull/394 this PR is to fix the scoring of the query for "Angkor Wat".
Pelias is currently giving the [OSM record](https://www.openstreetmap.org/way/91217761) a negative popularity as it's tagged `abandoned:amenity=place_of_worship`. 
We originally assumed that `abandoned:amenity` meant it was no longer important but that doesn't seem to be the case, either it's mis-tagged or we're interpreting the tag wrong. The [OSM wiki](https://wiki.openstreetmap.org/wiki/Key:abandoned:) seems to confirm our view, but who knows 🤷‍♂️ .
This PR maintains the negative scoring for all `abandoned` and `abandoned:*` tags with a single exception for `abandoned:amenity=place_of_worship`.
Currently that only affects [421 …
> popularity: do not penalize abandoned:amenity=place_of_worship

- package.json
I was investigating why the autocomplete query "Statue of Liberty" was not returning https://www.openstreetmap.org/way/32965412 when I discovered that the `pelias/model` version was well out-of-date and missing some features from the last year or so.
We were pinning `^7.2.1` which is from `10 June 2020`, this PR brings it up-to-date with the latest `^9.1.0`
https://github.com/pelias/model/tags
In particular `8.1.0` is very beneficial because it will reduce some of the TF/IDF scoring issues such as for the Statue of Liberty.
> chore: upgrade pelias-model to latest version

- package.json
upgrade pbf2json to latest version
prior to https://github.com/pelias/pbf2json/pull/99 the builds were being produced manually, so this should have a couple effects:
- bring in a more stable version which we know was built by CI
- brings in [changes since the previous version](https://github.com/pelias/pbf2json/releases).
the `end-to-end` and `unit` tests showed no changes so it seems to be innocuous 
[edit] hmm well at least locally 🤷 
It's hard to tell which version we are currently running in docker images but this is more explicit and avoids `6.8.0` which had a binary packing issue.
> upgrade pbf2json to latest version

- config/category_map.js
- config/localized_name_keys.js
- config/popularity_map.js
- stream/category_mapper.js
- stream/popularity_mapper.js
- stream/tag_mapper.js
- test/stream/tag_mapper.js
I was interested in https://github.com/pelias/openstreetmap/issues/557, it seems that we are using the [in operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in) / [for ... in](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in) syntax which iterates over all properties "including inherited enumerable properties".
A quick `git grep` shows other usages of that syntax in this lib which might need attention too.
closes https://github.com/pelias/openstreetmap/issues/557
> tag_mapper: skip inherited enumerable properties

- stream/tag_mapper.js
- test/stream/tag_mapper.js
Some addresses are failing to deduplicate because of minor differences in the expansion/contraction of diagonals:
This PR is very basic, it simply replaces the expanded form of these diagonals (in English only) where found in a street field.
We have a more advanced strategy for `openaddresses` in https://github.com/pelias/openaddresses/pull/477 which I'd like to port over to this repo too at some point, one difficulty with that is detecting the language appropriately.
This PR is a very simple fix in the interim.
The `pelias/schema` codebase has [synonym mappings](https://github.com/pelias/schema/blob/7eca249ea3657f08d4e758c5351a18b3ec79df8f/synonyms/directionals/en.txt#L16) which will allow matching to work in both forms.
> tag_mapper: contract english diagonals for street addresses

- package.json
- stream/tag_mapper.js
This package has an open [security vulnerability](https://github.com/advisories/GHSA-7wpw-2hjm-89gp), but can easily be replaced by the Lodash [_.merge](https://docs-lodash.com/v4/merge/) function.
> Remove 'merge' package

- .dockerignore
While running some other analysis on our docker images I noticed that the Docker image for OSM will include the ~30MB of PBF files and test fixtures we use in our end-to-end tests.
Currently, we don't run anything but the unit tests during the Docker image build, so these files are never used.
Since it will save quite a bit of space and reduce network usage every time someone downloads a new copy of the OSM Docker image, removing them seems like the right call.
> Add large test fixtures to `.dockerignore`

- config/features.js
- schema/address_karlsruhe.js
- stream/addresses_without_street.js
- stream/importPipeline.js
- test/run.js
- test/stream/addresses_without_street.js
- test/stream/importPipeline.js
Because of missing tag `addr:place` in schema, importer skip a lot of addresses. For example in Mannheim, DE most of the streets named with letter is not imported.
So to fix this, I added missing tag.
> Added missing street mapping

- schema/address_karlsruhe.js
- schema/address_naptan.js
- schema/address_osm.js
- schema/address_tiger.js
- schema/name_osm.js
- stream/address_extractor.js
- stream/tag_mapper.js
- test/run.js
- test/stream/tag_mapper.js
- test/util/parseSemicolonDelimitedValues.js
- util/parseSemicolonDelimitedValues.js
replaces https://github.com/pelias/openstreetmap/pull/581
> note: commits need to be squashed and correctly prefixed (with `feat:`) before merging.
This PR adds support for semi-colon delimited names in OSM.
see: https://wiki.openstreetmap.org/wiki/Talk:Semi-colon_value_separator
Compared to #581 I added:
- Cleaning parsed values (trimming whitespace and filtering empty strings, ie. `''` or `foo;;bar`)
- Support for semi-colon delimited names in lang fields (ie. `name:en`) as well as those in `NAME_SCHEMA`.
- Moved `parseSemicolonDelimitedValues()` function to it's own module as it's used in the `address_extractor` too.
- Removed this weird `_primary` key from `NAME_SCHEMA` which probably seemed like a good idea at the time but is unnecessarily confusing.
- Updated the code which hunts …
> support semi-colon delimited names
